apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - redis.yaml
  - deployment.yaml
  - routes.yaml
  - image-automation.yaml
components:
  - ../gateway-component
patches:
  - target:
      kind: Gateway
      name: APPNAME-gateway
    patch: |
      - op: replace
        path: /metadata/name
        value: hello-gateway
      - op: replace
        path: /metadata/annotations/service.beta.kubernetes.io~1azure-dns-label-name
        value: ${HELLOORLEONS_DNS_LABEL}
      - op: replace
        path: /spec/listeners/1/hostname
        value: ${HELLOORLEONS_GATEWAY_HOSTNAME}
      - op: replace
        path: /spec/listeners/1/tls/certificateRefs/0/name
        value: hello-gateway-tls
