apiVersion: v1
kind: Service
metadata:
  name: APPNAME-silo
  namespace: REPLACE_NAMESPACE
spec:
  clusterIP: None
  selector:
    app: REPLACE_APP
  ports:
    - name: silo
      port: 11111
    - name: gateway
      port: 30000
